.TH "galternatives" "1"
.SH "NAME"
galternatives \- A front-end to the update-alternatives
.SH "SYNOPSIS"
\fBgalternatives
.SH "DESCRIPTION"
.B galternatives
is a front-end to the Debian update-alternatives tools. galternatives allows the user to specify a preferred application to handle commonly-used commands.
.SH "AUTHOR"
.PP
This manual page was written by Andrew Burton adb@iinet.net.au for the \fBDebian GNU/Linux\fP system (but may be used by others).
